#ifndef __FLABEE_CONSTANTS__
#define __FLABEE_CONSTANTS__

#define WINDOW_TITLE "Flabee"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define BEE_POSITION_X (WINDOW_WIDTH / 20.0f)
#define BEE_START_POSITION_Y (WINDOW_HEIGHT / 2.0f)
#define BEE_SIZE (WINDOW_WIDTH / 24.0f)
#define BEE_GRAVITY (WINDOW_HEIGHT * 2.0f)
#define BEE_JUMP_SPEED (WINDOW_HEIGHT * -0.7f)

#define OBSTACLE_WIDTH (WINDOW_WIDTH / 12.0f)
#define OBSTACLE_GAP_HEIGHT (BEE_SIZE * 3.5f)
#define OBSTACLE_MIN_GAP_Y (OBSTACLE_GAP_HEIGHT / 2.0f)
#define OBSTACLE_MAX_GAP_Y (WINDOW_HEIGHT - OBSTACLE_MIN_GAP_Y - OBSTACLE_GAP_HEIGHT)
#define OBSTACLE_SPACE_X (WINDOW_WIDTH / 3)
#define OBSTACLE_SPEED_X (WINDOW_WIDTH / -6.0f)

#endif
