#ifndef __FLABEE_CONSTANTS__
#define __FLABEE_CONSTANTS__

#define WINDOW_TITLE "Flabee"
#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define BEE_POSITION_X (WINDOW_WIDTH / 20.0f)
#define BEE_START_POSITION_Y (WINDOW_HEIGHT / 2.0f)
#define BEE_SIZE (WINDOW_WIDTH / 24.0f)
#define BEE_SPRITE_SIZE 16.0f
#define BEE_GRAVITY (WINDOW_HEIGHT * 2.0f)
#define BEE_JUMP_SPEED (WINDOW_HEIGHT * -0.7f)

#define OBSTACLE_WIDTH (WINDOW_WIDTH / 12.0f)
#define OBSTACLE_GAP_HEIGHT (BEE_SIZE * 3.5f)
#define OBSTACLE_MIN_GAP_Y (OBSTACLE_GAP_HEIGHT / 2.0f)
#define OBSTACLE_MAX_GAP_Y (WINDOW_HEIGHT - OBSTACLE_MIN_GAP_Y - OBSTACLE_GAP_HEIGHT)
#define OBSTACLE_SPACE_X (WINDOW_WIDTH / 3)
#define OBSTACLE_SPEED_X (WINDOW_WIDTH / -6.0f)

#define SCOREBOARD_SPRITE_WIDTH 256.0f
#define SCOREBOARD_SPRITE_HEIGHT 160.0f
#define SCOREBOARD_SPRITE_SCALE 2.0f
#define SCOREBOARD_WIDTH (SCOREBOARD_SPRITE_WIDTH * SCOREBOARD_SPRITE_SCALE)
#define SCOREBOARD_HEIGHT (SCOREBOARD_SPRITE_HEIGHT * SCOREBOARD_SPRITE_SCALE)
#define SCOREBOARD_POSITION_X ((WINDOW_WIDTH - SCOREBOARD_WIDTH) / 2.0f)
#define SCOREBOARD_POSITION_Y ((WINDOW_HEIGHT - SCOREBOARD_HEIGHT) / 2.0f)

#define SCORE_POSITION_Y (55.0f * SCOREBOARD_SPRITE_SCALE)
#define BEST_SCORE_POSITION_Y (110.0f * SCOREBOARD_SPRITE_SCALE)

#define DIGITS_SPRITE_WIDTH 8.0f
#define DIGITS_SPRITE_HEIGHT 8.0f
#define DIGITS_SPRITE_SCALE 4.0f
#define DIGITS_WIDTH (DIGITS_SPRITE_WIDTH * DIGITS_SPRITE_SCALE)
#define DIGITS_HEIGHT (DIGITS_SPRITE_HEIGHT * DIGITS_SPRITE_SCALE)

#endif
